python ./scripts/train.py \
  --method attnres \
  --model_dir ./model \
  --train_path ./data/boolq/train.json \
  --save_dir ./checkpoints/attnres_boolq \
  --max_length 512 \
  --num_train_epochs 3 \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --learning_rate 2e-4 \
  --logging_steps 10 \
  --save_strategy epoch \
  --attnres_lookback 8 \
  --attnres_gate_init 0.0 \
  --use_wandb \
  --wandb_project  \
  --wandb_run_name  \
  --wandb_entity 
